### ISSUE TITLE
trigger autocmd QuickFixCmdPost

### ISSUE THREAD

**Issue by Konfekt** [djmoch/vim-makejob#19]
There is an autocmd event `QuickFixCmdPost` that is called after completion of `make` for example. How about `MakeJob` doing an `doautocmd QuickFixCmdPost` after running the job? For example, the event
```
autocmd QuickFixCmdPost make cwindow | wincmd p
```
opens the `quickfix` window after compilation (by make) is completed.

**Comment by Konfekt** [comment]
Similarly, how about triggering `QuickFixCmdPre` before running a MakeJob?

**Comment by djmoch** [comment]
This is already being done. See `s:InitAutocmd`.

**Comment by Konfekt** [comment]
Thanks, true! Using the above autocmd as a test case, The misunderstanding was caused by there being no file:line errors appearing, so `0` findings, and therefore the quickfix window not popping up, even though `make` produced a lot of messages, but not of the format `file:line`. If there are messages of the format `file:line`, that is findings as MakeJob calls them, then indeed the quickfix windows shows up.
