### ISSUE TITLE
exception on switching buffers

### ISSUE THREAD

**Issue by Konfekt** [djmoch/vim-makejob#23]
Today a different exception was thrown on switching from a buffer with a Makejob autocommand. It read:
```vim
Error detected while processing function <SNR>236_JobHandler:
line   13:
E684: list index out of range: 0
E116: Invalid arguments for function win_gotoid
```

**Comment by djmoch** [comment]
@Bakudankun, any ideas on this?

**Comment by Bakudankun** [comment]
It can occur when MakeJob's window is somehow closed when the job ends.
`JobHandler()` assumes MakeJob window exists (from before my change).

I think it should check if `win_findbuf(l:job['srcbufnr'])` is empty list (at [line 69](https://github.com/djmoch/vim-makejob/blob/master/plugin/makejob.vim#L69)).

**Comment by Konfekt** [comment]
Both error messages (that of this issue and that of https://github.com/djmoch/vim-makejob/issues/22) are thrown by the automatic command `autocmd BufWrite noautocmd silent MakeJob!` which is mostly triggered by `autocmd FocusLost   * nested silent! wall`.

**Comment by djmoch** [comment]
I’ll try to reproduce, and then try out @bakudankun’s suggestion as soon as I have an opportunity, but that might be a few days. In the meantime, pull requests are always welcome. :)

**Comment by Konfekt** [comment]
Despite the `noautocmd` the quickfix window still pops up, probably due to,
```vim
autocmd QuickFixCmdPost make nested redraw! | cwindow | wincmd p
```
which probably causes the issue.

**Comment by djmoch** [comment]
@Konfekt, can you try the bugfix branch and see if that fixes your issue?

**Comment by Konfekt** [comment]
Ok, thank you.

**Comment by Konfekt** [comment]
At some point it threw
```vim
Error detected while processing function <SNR>230_JobHandler:
line   27:
E681: Buffer is not loaded
```
and closed the buffer wherein I was editing..

**Comment by Konfekt** [comment]
Though MakeJob perfectly suits my mere needs, none of these errors occur with `AsyncRun`, which  might give some hints.

**Comment by djmoch** [comment]
I've looked at AsyncRun before, and didn't find much helpful with respect to this problem. That isn't to say I don't have a lot I could learn about buffer management, I'm just not sure that's the place to look.

The core issue is due to the fact that, like @Bakudankun commented earlier, I implicitly assumed the source buffer would always exist when `JobHandler` executes. Now that the (bad) assumption has been brough to my attention, it's just a matter of stepping back and taking a look at the handler to figure out how to harden it against missing buffers.

I hope to have something this week. In the meantime, I apologize for the issues.

**Comment by djmoch** [comment]
Okay, I have another attempt that seems to me to resolve several of these issues. Unfortunately, @Konfekt, I need to ask you to run it through the ringer as I don't know if I have enough insight into your use case to have a high level of confidence.

Please try commit 150b4bed955492051237b982393bbdb69e7a043b on the bugfix branch when you get a chance.

**Comment by Konfekt** [comment]
Ok. Thanks for your efforts. 

Regarding in insight into testing it yourself, it is a make job run on saving the buffer. As in https://github.com/djmoch/vim-makejob/issues/23#issuecomment-378222913, it is achieved by

`autocmd BufWrite noautocmd silent MakeJob!` which is mostly triggered by `autocmd FocusLost * nested silent! wall`.

**Comment by Konfekt** [comment]
It threw an error, after the command having been triggered by `FocusLost`,
```vim
Error detected while processing function <SNR>227_JobHandler:
line   42:
E681: Buffer is not loaded
```

**Comment by djmoch** [comment]
Bummer. Okay. 

Now that I understand your `autocmd` config, I can try to reproduce this myself and hopefully avoid this back-and-forth. Hopefully I’ll get to take another look in the next few days. 

Thanks for your patience.

**Comment by Konfekt** [comment]
It is also important that the quickfix window is openened by
```vim
autocmd QuickFixCmdPost make nested redraw! | cwindow | wincmd p
```

**Comment by djmoch** [comment]
Can you see if 2b443578e930b61efa527151e2cfca36e8926e57 fixes your issue

**Comment by Konfekt** [comment]
Okay, will revert back to MakeJob instead of AsyncRun for a while and see if everything runs smoothly.

**Comment by Konfekt** [comment]
The `no mapping defined` error message reoccurred, but now there is also the problem that once a makejob is run, no other run is allowed, there is the error message
```vim
make already running
```
while trying `MakeJobStop` yields
```vim
Error detected while processing function <SNR>246_JobStop:
line   21:
Not in a MakeJob buffer, and none specified
```

**Comment by djmoch** [comment]
Finally merged into master. Send me an email if you're still having issues.
