### ISSUE TITLE
Makejob failing, cannot debug

### ISSUE THREAD

**Issue by apuignav** [djmoch/vim-makejob#25]
Hi!

I'm using vim-makejob with the following make prg:

```set makeprg=([[\ -f\ Makefile\ ]]\ &&\ (make\ $*;\ true)\\\|\\\|\ latexmk\ -lualatex\ \"%\"\ $*)```

This works fine with `:make`, but when I run `:MakeJob` it fails to run (`Return 122 with findings`) and the quickfix list is empty. There is no Makefile. 

I suspect this may have to be with the complicated logic of my `makeprg` but I don't know how to debug it. Any hints?

**Comment by djmoch** [comment]
Hello. Sorry for the slow turnaround. I don't actually remember getting a notification on this.

`:copen` should should any errors. Barring that, something like (Scriptease)[https://github.com/tpope/vim-scriptease] can aid using Vim's built-in (debugging)[http://vimdoc.sourceforge.net/htmldoc/repeat.html#debug-scripts] capabilities.

**Comment by djmoch** [comment]
I'm moving development to my [personal website](https://git.danielmoch.com/vim-makejob.git). Feel free to send me an email if you're still having issues.
