### ISSUE TITLE
optional preview window

### ISSUE THREAD

**Issue by bounceme** [djmoch/vim-makejob#8]
could it be an option to show the preview window? I see https://github.com/djmoch/vim-makejob/blob/master/plugin/makejob.vim#L151 so this is not a vim behaviour by default, thanks

**Comment by bounceme** [comment]
actually, wouldn't echoing the number of errors be a better ui? I like this concept now that i think about it but the window shift is kind of distracting if using this plugin with autocmds

**Comment by djmoch** [comment]
Showing the real-time activity of the job can be useful for long-running
jobs, so it's easy to imagine somebody wanting the window open for some
jobs but not others. That presents a bit of a challenge on how best to
accommodate that. Here's what I'm thinking:

Offer a global option, g:makejob_hide_preview_window, that sets the
behavior globally. Then have a buffer-local that allows overriding on a
more granular bases: b:makejob_override_preview_behavior.

Would that get you what you want?

**Comment by bounceme** [comment]
hmm, i've come around to to it actually. it is nice to see output and to know when a job is done

**Comment by djmoch** [comment]
Closed by bd891d3c3ede61626db4af0110f1ebb0ffd023c0
