### ISSUE TITLE
More Options

### ISSUE THREAD

**Issue by EvilPudding** [djmoch/vim-makejob#9]
Is there anyway to have make output (actual makefile stdout) in a fixed split? Whenever I compile I can't take much advantage if it being asynchronous since the window keeps bouncing up and down.

Is there anyway currently to run a specific makefile option like `:make run`?

**Comment by djmoch** [comment]
Maybe I'm being dense, but I'm not sure what you mean about the window bouncing up and down. MakeJob should just open a split below the current buffer (similar to lopen) and stdout and stderr should appear there. 

I also tested running individual make targets and it should work fine. Syntax would be :MakeJob! run, assuming your compiler is set appropriately in Vim.

**Comment by EvilPudding** [comment]
Thanks for the tip on how to run specific makefile targets, hadn't figuret it out.

My working window bounces up and down when the split opens and closes, so my code moves up and down.

**Comment by djmoch** [comment]
Out of curiosity, does it behave the same way as :lopen? I'm still trying to get a feel for what you're describing.

**Comment by djmoch** [comment]
I see what you're talking about, but this is standard Vim behavior that I'm not able to override.

One option that would alleviate this problem would be for me to implement #8. Once that happens, you'll be able to set an option so the preview buffer is not visible, and the result should be a less disruptive experience.

**Comment by djmoch** [comment]
Closing as wontfix/addressed in #8.
